
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:age itemname="年龄" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:age>



<field:phone itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:qq itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq>

<field:mail itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mail>
