<li>
					<!--标签旗帜---><div class="jiaoluo"></div>
					<div class="tagg"><a>[field:typelink/]</a></div>
					<div class="tagg1"></div>
					<!--标题--->
					<div class="biaotii clearfix">
						<h2 class="fl"><a href="[field:arcurl/]">[field:title/]</a></h2>
						<span class="rt">[field:pubdate function="GetDateMK(@me)"/]</span>
					</div>
					<!--- 缩略图简介---->
					<div class="slt"><a href="[field:arcurl/]"><img src="[field:picname/]"></a></div>
					<div class="zww">[field:description/]... 
					<br><a href="[field:arcurl/]"> <查看全文> </a>
					</div>
					<!-- 关键词---->
					<div class="gongn clearfix">
						<div class="tagss rt">本文关键字：  [field:id function=GetTags(@me)/]</div>			
					</div>
				</li>