<field:webpic itemname="电脑端图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:webpic>
<field:phonepic itemname="手机端图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:phonepic>

<field:piclinks itemname="图片链接地址" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="http://www.eb3usa.com/news/others/2017/0526/421.html"  maxlength="250" page="">
</field:piclinks>
