<?php
$z[0]=Array("field","",199,218);
$z[0][4]['name']="title";
$z[1]=Array("global","",219,245);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",292,351);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",391,420);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",2875,2910);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",13793,13830);
$z[5][4]['filename']="footer.htm";

?>