<?php
$z[0]=Array("field","",204,223);
$z[0][4]['name']="title";
$z[1]=Array("global","",224,250);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",298,357);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",398,427);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",2965,3000);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",14051,14088);
$z[5][4]['filename']="footer.htm";

?>