<?php
$z[0]=Array("channel","\r\n  						<li class=\"nav__item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li> \r\n  						",6707,6843);
$z[0][4]['type']="top";
$z[1]=Array("arclist","\r\n					<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n					",9182,9312);
$z[1][4]['row']="1";
$z[1][4]['typeid']="1";
$z[1][4]['flag']="h";
$z[1][4]['titlelen']="250";
$z[2]=Array("arclist","\r\n        				<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n        				",9461,9646);
$z[2][4]['row']="15";
$z[2][4]['typeid']="1";
$z[2][4]['noflag']="h";
$z[2][4]['orderby']="id";
$z[2][4]['orderway']="desc";
$z[2][4]['titlelen']="250";

?>