<?php
$z[0]=Array("channel","\r\n  						<li class=\"nav__item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li> \r\n  						",6707,6843);
$z[0][4]['type']="top";
$z[1]=Array("arclist","\r\n				<li><a>\r\n					<img src=\"[field:webpic/]\" class=\"fly\">\r\n					<img src=\"[field:phonepic/]\" class=\"fly2\">\r\n				</a></li>\r\n				",7258,7509);
$z[1][4]['row']="10";
$z[1][4]['typeid']="15";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['addfields']="webpic,phonepic";
$z[1][4]['channelid']="18";
$z[2]=Array("arclist","\r\n					<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n					",9161,9291);
$z[2][4]['row']="1";
$z[2][4]['typeid']="1";
$z[2][4]['flag']="h";
$z[2][4]['titlelen']="250";
$z[3]=Array("arclist","\r\n        				<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n        				",9440,9625);
$z[3][4]['row']="15";
$z[3][4]['typeid']="1";
$z[3][4]['noflag']="h";
$z[3][4]['orderby']="id";
$z[3][4]['orderway']="desc";
$z[3][4]['titlelen']="250";

?>