<?php
$z[0]=Array("channel","\n  						<li class=\"nav__item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li> \n  						",6505,6639);
$z[0][4]['type']="top";
$z[1]=Array("arclist","\n				<li>\n<a  href=\"[field:piclinks/]\" target=\"_blank\">\n					<img src=\"[field:webpic/]\" class=\"fly\">\n					<img src=\"[field:phonepic/]\" border=\"0\" class=\"fly2\" >		\n</a>\n			 </li>\n				",7037,7354);
$z[1][4]['row']="10";
$z[1][4]['typeid']="15";
$z[1][4]['orderby']="weight";
$z[1][4]['orderway']="desc";
$z[1][4]['addfields']="webpic,phonepic,piclinks";
$z[1][4]['channelid']="18";
$z[2]=Array("arclist","\n					<a href=\"[field:arcurl/]\">[field:title/]</a>\n					",8956,9084);
$z[2][4]['row']="1";
$z[2][4]['typeid']="1";
$z[2][4]['flag']="h";
$z[2][4]['titlelen']="250";
$z[3]=Array("arclist","\n        				<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n        				",9227,9410);
$z[3][4]['row']="15";
$z[3][4]['typeid']="1";
$z[3][4]['noflag']="h";
$z[3][4]['orderby']="id";
$z[3][4]['orderway']="desc";
$z[3][4]['titlelen']="250";

?>