<?php
$z[0]=Array("channel","\r\n            <li class=\"nav__item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",6380,6523);
$z[0][4]['type']="top";
$z[1]=Array("arclist","\r\n        <li><a href=\"[field:arcurl /]\">\r\n          <div class=\"info-tup\"><img src=\"[field:picname/]\"></div>\r\n          <div class=\"info-date\">[field:pubdate function=\"GetDateMK(@me)\"/]</div>\r\n          <p class=\"info-title\">[field:title/]</p>\r\n          <p class=\"info-jj\">[field:description/]...</p>\r\n          </a> </li>\r\n        ",22805,23225);
$z[1][4]['row']="6";
$z[1][4]['typeid']="1";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[1][4]['flag']="c";
$z[2]=Array("flink","[field:link/]",25746,25784);

?>