<?php
$z[0]=Array("field","",124,143);
$z[0][4]['name']="title";
$z[1]=Array("global","",144,170);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",218,277);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",318,347);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1347,1382);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","	\r\n					<div class=\"biaotii clearfix\">\r\n						<h2 class=\"fl\"><a style=\"font-size:16px\">[field:title/]</a></h2>\r\n						<span class=\"rt\">[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n					</div>\r\n		",1713,1981);
$z[5][4]['pagesize']="136";
$z[5][4]['orderby']="id";
$z[5][4]['orderway']="desc";
$z[6]=Array("pagelist","",2040,2104);
$z[6][4]['istitem']="index,pre,next,end,info";
$z[6][4]['listsize']="5";
$z[7]=Array("tag"," \r\n																	<li><a href='[field:link/]' target=\"_blank\">[field:tag /]</a> </li>\r\n																	",3853,4011);
$z[7][4]['row']="30";
$z[7][4]['sort']="new";
$z[7][4]['getall']="0";
$z[8]=Array("include","",4185,4227);
$z[8][4]['filename']="news-footer.htm";

?>