<?php
$z[0]=Array("field","",203,222);
$z[0][4]['name']="title";
$z[1]=Array("global","",223,249);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",297,356);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",397,426);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",2500,2535);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",7893,7930);
$z[5][4]['filename']="footer.htm";

?>