<?php
$z[0]=Array("field","",198,217);
$z[0][4]['name']="title";
$z[1]=Array("global","",218,244);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",291,350);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",390,419);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",2420,2455);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",7698,7735);
$z[5][4]['filename']="footer.htm";

?>