<?php
$z[0]=Array("global","",128,154);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",202,232);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",273,300);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",552,587);
$z[3][4]['filename']="head.htm";
$z[4]=Array("tag","\r\n						<a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n						",945,1075);
$z[4][4]['row']="60";
$z[4][4]['sort']="new";
$z[5]=Array("tag","\r\n						<a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n						",1188,1320);
$z[5][4]['row']="60";
$z[5][4]['sort']="month";
$z[6]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]' target=\"_blank\">[field:tag /]</a>\r\n            ",1424,1584);
$z[6][4]['row']="100";
$z[6][4]['sort']="rand";
$z[7]=Array("include","",1704,1746);
$z[7][4]['filename']="news-footer.htm";

?>