<?php
$z[0]=Array("global","",128,154);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",202,232);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",273,300);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",524,559);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",858,883);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("field","",940,960);
$z[5][4]['name']="title";
$z[6]=Array("list","		\r\n				<li>\r\n					<!--标签旗帜---><div class=\"jiaoluo\"></div>\r\n					<div class=\"tagg\"><a>[field:typelink/]</a></div>\r\n					<div class=\"tagg1\"></div>\r\n					<!--标题--->\r\n					<div class=\"biaotii clearfix\">\r\n						<h2 class=\"fl\"><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n						<span class=\"rt\">[field:pubdate function=\"GetDateTimeMK(@me)\" /]</span>\r\n					</div>\r\n					<!--- 缩略图简介---->\r\n					<div class=\"slt\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"></a></div>\r\n					<div class=\"zww\">[field:description/]... <br>\r\n						<a href=\"[field:arcurl/]\"> <查看全文> </a>\r\n					</div>\r\n					<!-- 关键词---->\r\n					<div class=\"gongn clearfix\">\r\n						<div class=\"tagss rt\">本文关键字：  [field:id function=GetTags(@me)/]</div>			\r\n					</div>\r\n				</li>\r\n		",1045,1906);
$z[6][4]['pagesize']="6";
$z[6][4]['orderby']="id";
$z[6][4]['orderway']="desc";
$z[7]=Array("pagelist","",1988,2052);
$z[7][4]['istitem']="index,pre,next,end,info";
$z[7][4]['listsize']="5";
$z[8]=Array("channel","	\r\n					<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n				",3510,3631);
$z[8][4]['reid']="1";
$z[8][4]['type']="son";
$z[9]=Array("tag"," \r\n					 <li><a href='[field:link/]'>[field:tag /]</a> </li>\r\n					 ",3800,3920);
$z[9][4]['row']="30";
$z[9][4]['sort']="new";
$z[9][4]['getall']="0";
$z[10]=Array("include","",4065,4107);
$z[10][4]['filename']="news-footer.htm";

?>